@extends('layouts.app')
@section('title', 'AI Report Generator')
@section('content')
<div class="page-header">
    <div><h4 class="fw-semibold mb-1"><i class="fas fa-file-alt me-2"></i>AI Report Generator</h4>
        <nav aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li><li class="breadcrumb-item"><a href="#">AI</a></li><li class="breadcrumb-item active">Report Generator</li></ol></nav>
    </div>
    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#reportModal"><i class="fas fa-plus me-1"></i>Generate New Report</button>
</div>

<div class="card shadow-sm border-0">
    <div class="card-body p-0">
        <x-table :headers="['#','Title','Type','Status','Generated By','Created At','Actions']">
            @forelse($reports as $r)
            <tr>
                <td>{{ $loop->iteration + ($reports->currentPage()-1)*$reports->perPage() }}</td>
                <td class="fw-semibold">{{ $r->title ?? 'Untitled' }}</td>
                <td><span class="badge bg-info">{{ ucfirst(str_replace('_', ' ', $r->type ?? 'custom')) }}</span></td>
                <td>
                    @php
                        $s = $r->status ?? 'pending';
                        $sc = $s == 'completed' ? 'success' : ($s == 'processing' ? 'warning' : 'secondary');
                    @endphp
                    <span class="badge bg-{{ $sc }}">{{ ucfirst($s) }}</span>
                </td>
                <td>{{ $r->generated_by_name ?? $r->user->name ?? '-' }}</td>
                <td>{{ $r->created_at ? \Carbon\Carbon::parse($r->created_at)->format('M d, Y H:i') : '-' }}</td>
                <td>
                    <button class="btn btn-sm btn-outline-info view-report-btn" data-result='{{ json_encode($r->result ?? $r->parameters ?? []) }}' data-title="{{ $r->title }}" data-bs-toggle="modal" data-bs-target="#viewReportModal">
                        <i class="fas fa-eye"></i> View
                    </button>
                </td>
            </tr>
            @empty
            <tr><td colspan="7" class="text-center text-muted py-4">No reports found</td></tr>
            @endforelse
        </x-table>
    </div>
</div>
<x-pagination :paginator="$reports" />

<x-modal id="reportModal" title="Generate New Report">
    <form method="POST" action="{{ route('ai.report-generator.store') }}" id="reportForm">
        @csrf
        <div class="row g-2">
            <div class="col-md-12"><x-form-input name="title" label="Report Title" required placeholder="Enter report title" /></div>
            <div class="col-md-12">
                <x-form-select name="type" label="Report Type" :options="['academic' => 'Academic', 'financial' => 'Financial', 'attendance' => 'Attendance', 'student_performance' => 'Student Performance', 'custom' => 'Custom']" required />
            </div>
            <div class="col-md-12"><x-form-textarea name="parameters" label="Parameters (JSON)" rows="4" placeholder='{"key": "value"}' /></div>
        </div>
    </form>
    <x-slot:footer><button class="btn btn-primary" type="submit" form="reportForm"><i class="fas fa-wand-magic-sparkles me-1"></i>Generate</button><button class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button></x-slot:footer>
</x-modal>

<x-modal id="viewReportModal" title="Report Result">
    <pre id="reportResultContent" class="bg-light p-3 rounded" style="max-height: 400px; overflow-y: auto; font-size: 0.85rem;"></pre>
    <x-slot:footer><button class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button></x-slot:footer>
</x-modal>

@push('scripts')
<script>
    $(document).on('click', '.view-report-btn', function() {
        var title = $(this).data('title');
        var result = $(this).data('result');
        $('#viewReportModal .modal-title').text('Report: ' + title);
        $('#reportResultContent').text(typeof result === 'string' ? result : JSON.stringify(result, null, 2));
    });
</script>
@endpush
@endsection
